### ISSUE TITLE
Make window draggable

### ISSUE THREAD

**Issue by juliangruber** [filecoin-project/filecoin-station#173]
Currently on macOS you can't move the window, because there's no titlebar and none of the elements are marked as draggable.

Make everything draggable, except where it's inappropriate, most notably on links, buttons and other form elements.

```css
.draggable {
  -webkit-user-select: none;
  -webkit-app-region: drag;
}

.non-draggable {
  -webkit-app-region: no-drag;
}
```
